### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by uzelac** [troykelly/homeassistant-dynalite#1]
Hi

Have an Dynalite at home, trying to figure it out.
How do you install this component, cant find any readme/info on it.

Thanks

**Comment by troykelly** [comment]
Hi @uzelac - Thank's for reaching out.
This is absolutely a work in progress, it takes a log of configuring.
I will try and get some documentation together over the weekend.

**Comment by troykelly** [comment]
@uzelac Best to use the component instead - it's https://github.com/troykelly/hassio-component-dynalite
